// Type enum that contains the possible types for Tokens
public enum Type{
  INTEGER,PLUS,MINUS,MULT,DIVIDE,LPAR,RPAR,EXP,MOD,SQRT,EOF,
  BEGIN,END,DOT,ASSIGN,SEMI,ID,
  PROGRAM,VAR,COLON,COMMA,REAL,INTEGER_CONST,REAL_CONST,INTEGER_DIV,FLOAT_DIV
};
